import { StageLedger } from '../memory';

export const name = 'Planner';
export const temperature = 0.3;
export const maxTokens = 1536;

export const systemPrompt = `You are the Planner Agent in a multi-agent autonomous software engineering pipeline following the Spiral SDLC model.

Your responsibility is to transform the Queen Agent's canonical project context into a complete implementation plan for an MVP. You decide WHAT must be built and WHAT technologies are required, but NOT HOW they are implemented.

Your input is the validated, immutable canonical context generated by the Queen Agent.

Your objectives are:
1. Analyze the project context and MVP scope.
2. Select the most appropriate technology stack based on project requirements and constraints.
3. Define the complete list of MVP features required to satisfy the project goal, each with a stable ID and an explicit mvpReference back to the Queen's mvpId.
4. Define the functional requirements for every feature.
5. Define non-functional requirements (security, performance, scalability, usability, maintainability, accessibility, reliability) whenever applicable.
6. Define project deliverables required to complete the MVP.
7. Provide explicit instructions for every downstream agent that consumes this plan.
8. Produce a single structured JSON document marked as the canonical implementation plan.

Rules:
- Scale the features list and backlog items directly to the project's size. If the request is a lightweight script or utility, output a single simple feature representing the script/tool rather than an enterprise backlog.
- Adapt the recommended technology stack dynamically. If the user requested a specific stack (e.g., Python, Streamlit, shell script), select it exactly. If they request a simple script, set database, authentication, and deployment to "none" or "local".
- Do not design the system architecture.
- Do not generate database schemas.
- Do not design APIs.
- Do not create UI layouts.
- Do not write implementation logic or source code.
- Every feature must directly support the MVP scope defined by the Queen, and must carry id and mvpReference fields.
- Do not introduce features outside the approved scope.
- Output ONLY valid JSON matching the required schema.
- For fields not applicable, output "N/A".
- The generated JSON is marked "contextType": "canonical" and is immutable downstream.
- Every field required by the Planner Validation Contract must be present, including agentInstructions and features[].mvpReference.`;

export const schema = {
  type: 'object',
  properties: {
    contextType: { type: 'string', const: 'canonical' },
    projectName: { type: 'string' },
    mvpReference: { type: 'string' },
    recommendedTechStack: {
      type: 'object',
      properties: {
        frontend: { type: 'string' },
        backend: { type: 'string' },
        database: { type: 'string' },
        authentication: { type: 'string' },
        deployment: { type: 'string' },
        additionalTechnologies: { type: 'array', items: { type: 'string' } }
      },
      required: ['frontend', 'backend', 'database', 'authentication', 'deployment', 'additionalTechnologies']
    },
    features: {
      type: 'array',
      minItems: 1,
      items: {
        type: 'object',
        properties: {
          id: { type: 'string' },
          mvpReference: { type: 'string' },
          name: { type: 'string' },
          description: { type: 'string' },
          priority: { type: 'string', enum: ['Critical', 'High', 'Medium', 'Low'] }
        },
        required: ['id', 'mvpReference', 'name', 'description', 'priority']
      }
    },
    functionalRequirements: { type: 'array', items: { type: 'string' } },
    nonFunctionalRequirements: {
      type: 'object',
      properties: {
        security: { type: 'array', items: { type: 'string' } },
        performance: { type: 'array', items: { type: 'string' } },
        scalability: { type: 'array', items: { type: 'string' } },
        usability: { type: 'array', items: { type: 'string' } },
        maintainability: { type: 'array', items: { type: 'string' } },
        accessibility: { type: 'array', items: { type: 'string' } },
        reliability: { type: 'array', items: { type: 'string' } }
      },
      required: ['security', 'performance', 'scalability', 'usability', 'maintainability', 'accessibility', 'reliability']
    },
    deliverables: { type: 'array', items: { type: 'string' } },
    agentInstructions: {
      type: 'object',
      properties: {
        architect: { type: 'string' },
        system: { type: 'string' },
        designer: { type: 'string' },
        coder: { type: 'string' },
        tester: { type: 'string' },
        debugger: { type: 'string' },
        security: { type: 'string' }
      },
      required: ['architect', 'system', 'designer', 'coder', 'tester', 'debugger', 'security']
    }
  },
  required: ['contextType', 'projectName', 'mvpReference', 'recommendedTechStack', 'features', 'functionalRequirements', 'nonFunctionalRequirements', 'deliverables', 'agentInstructions']
};

export async function getContext(ledger: StageLedger): Promise<string> {
  const data = ledger.query('Planner', {
    fromAgent: 'Queen',
    select: ['domain', 'goal', 'primaryEntities', 'relationships', 'constraints', 'agentTasks']
  });
  return JSON.stringify({ Queen: data }, null, 2);
}
